// YardBoss — Seed Data  |  TransVega RV and Truck Center, Sebring FL

const APP_DATA = {
  owner: {
    name: 'Toby Herndon',
    initials: 'TH',
    email: 'toby@transvegalogistics.com',
    phone: '(863) 441-3444',
    address: '7406 HWY 27 North, Sebring, FL 33870',
    businessName: 'TransVega Logistics LLC'
  },

  lots: [
    {
      id: 'lot-1',
      name: 'TransVega RV and Truck Center',
      address: '7406 HWY 27 North',
      city: 'Sebring', state: 'FL', zip: '33870',
      totalSpaces: 140,
      status: 'active',
      amenities: [
        '24/7 Gated Access','Security Cameras','Full Hookups (30/50 Amp)',
        'Water & Sewer','WiFi Available','Dump Station','Truck Wash Bay',
        'On-Site Manager','Paved Surfaces','Lighting'
      ],
      spaceTypes: ['Class A RV','Class B/C RV','Travel Trailer','Fifth Wheel','Semi-Truck','Box Truck'],
      monthlyRates: {
        'Class A RV': 220,'Class B/C RV': 175,'Travel Trailer': 165,
        'Fifth Wheel': 190,'Semi-Truck': 295,'Box Truck': 225
      },
      image: null
    }
  ],

  tenants: [
    {
          "id": "t-001",
          "name": "Hilbert Garzia",
          "initials": "HG",
          "email": "hilbertgarza98@gmail.com",
          "phone": "",
          "company": "DURABLE EXPRESS BLACK",
          "lotId": "lot-1",
          "spaceNumber": "6",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-002",
          "name": "Victor Simon",
          "initials": "VS",
          "email": "247avenuex@gmail.com",
          "phone": "",
          "company": "Avenue Express  #1974 White Trailer",
          "lotId": "lot-1",
          "spaceNumber": "7",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Travel Trailer"
          },
          "plateState": "FL",
          "truckNumber": "125563",
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-003",
          "name": "Todd Tucker",
          "initials": "TT",
          "email": "toddrtucker@hotmail.com",
          "phone": "",
          "company": "SCHNEIDER # 89322",
          "lotId": "lot-1",
          "spaceNumber": "8",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": "133655",
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-004",
          "name": "Ivory Hunter",
          "initials": "IH",
          "email": "fattdaddytrucking@yahoo.com",
          "phone": "",
          "company": "FATT DADDY #041 Pl# JB95CN FL PETERBILT",
          "lotId": "lot-1",
          "spaceNumber": "9",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "Peterbilt",
                "model": "",
                "year": null,
                "plate": "JB95CN",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": "676680",
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-005",
          "name": "Ivory Hunter",
          "initials": "IH",
          "email": "fattdaddytrucking@yahoo.com",
          "phone": "",
          "company": "FATT DADDY #042 GREEN FREIGTHLINER only trailer",
          "lotId": "lot-1",
          "spaceNumber": "10",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "Freightliner",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-006",
          "name": "Luis Moyano",
          "initials": "LM",
          "email": "",
          "phone": "",
          "company": "#13 HORA EXPRESS RED -Trailer",
          "lotId": "lot-1",
          "spaceNumber": "11",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Travel Trailer"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-007",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "",
          "phone": "",
          "company": "",
          "lotId": "lot-1",
          "spaceNumber": "12",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": "#4240",
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-008",
          "name": "Urban Paul",
          "initials": "UP",
          "email": "",
          "phone": "",
          "company": "WHITE Trailer",
          "lotId": "lot-1",
          "spaceNumber": "13",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Travel Trailer"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-009",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "",
          "phone": "",
          "company": "",
          "lotId": "lot-1",
          "spaceNumber": "14",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-010",
          "name": "Yosbany Hernandez Aquino",
          "initials": "YH",
          "email": "yosbany2005@gmail.com",
          "phone": "3057937401",
          "company": "SABEL TRUCKING",
          "lotId": "lot-1",
          "spaceNumber": "15",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "autopay",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-011",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "carxpofl@gmail.com",
          "phone": "",
          "company": "truck with car hauler",
          "lotId": "lot-1",
          "spaceNumber": "16",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-012",
          "name": "Ray Redmon",
          "initials": "RR",
          "email": "",
          "phone": "",
          "company": "",
          "lotId": "lot-1",
          "spaceNumber": "17",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-013",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "",
          "phone": "",
          "company": "Ed 227527 US DOT 2355570",
          "lotId": "lot-1",
          "spaceNumber": "18",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-014",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "carxpofl@gmail.com",
          "phone": "",
          "company": "ONE GLOBAL LLC CAR HAULERS",
          "lotId": "lot-1",
          "spaceNumber": "19",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-015",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "carxpofl@gmail.com",
          "phone": "",
          "company": "ONE GLOBAL LLC CAR HAULERS",
          "lotId": "lot-1",
          "spaceNumber": "20",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-016",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "carxpofl@gmail.com",
          "phone": "",
          "company": "ONE GLOBAL LLC CAR HAULERS",
          "lotId": "lot-1",
          "spaceNumber": "21",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-017",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "carxpofl@gmail.com",
          "phone": "",
          "company": "ONE GLOBAL LLC CAR HAULERS",
          "lotId": "lot-1",
          "spaceNumber": "22",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-018",
          "name": "Giovanni Arrindell",
          "initials": "GA",
          "email": "carxpofl@gmail.com",
          "phone": "",
          "company": "ONE GLOBAL LLC CAR HAULERS",
          "lotId": "lot-1",
          "spaceNumber": "23",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-019",
          "name": "Lea Hardewijk",
          "initials": "LH",
          "email": "",
          "phone": "",
          "company": "",
          "lotId": "lot-1",
          "spaceNumber": "24",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-020",
          "name": "Tom Gallagher",
          "initials": "TG",
          "email": "",
          "phone": "",
          "company": "box truck(ice cream truck)  Shipping Container",
          "lotId": "lot-1",
          "spaceNumber": "25",
          "monthlyRate": 0,
          "startDate": "2025-11-01",
          "endDate": "2026-06-30",
          "status": "past",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Box Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-021",
          "name": "Bradley Hunter",
          "initials": "BH",
          "email": "",
          "phone": "954-465-3020",
          "company": "",
          "lotId": "lot-1",
          "spaceNumber": "26",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Travel Trailer"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-022",
          "name": "Joe Penn",
          "initials": "JP",
          "email": "joe@iprlogistics.com",
          "phone": "225-937-4716",
          "company": "RED #4248 - Clean & Take Pics for sale",
          "lotId": "lot-1",
          "spaceNumber": "27",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-023",
          "name": "David Perez",
          "initials": "DP",
          "email": "davidrogue79@aol.com",
          "phone": "(305) 394-3238",
          "company": "Werner Enterprises",
          "lotId": "lot-1",
          "spaceNumber": "28",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": "00138328",
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-024",
          "name": "Caden Byroadsn",
          "initials": "CB",
          "email": "",
          "phone": "",
          "company": "18ft truck 2008 black ford 250",
          "lotId": "lot-1",
          "spaceNumber": "29",
          "monthlyRate": 0,
          "startDate": "2026-02-11",
          "endDate": "2026-03-11",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "Ford",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-025",
          "name": "Daniel Oramas",
          "initials": "DO",
          "email": "oramasdaniel90@gmail.com",
          "phone": "8636776726",
          "company": "Panthers Trucking Service orange freightliner Pl#66AKRP FL SILVER TRAILER Brown Pick up Truck Pl# RKZI72",
          "lotId": "lot-1",
          "spaceNumber": "30",
          "monthlyRate": 0,
          "startDate": "2026-01-01",
          "endDate": "2026-01-31",
          "status": "past",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "Freightliner",
                "model": "",
                "year": null,
                "plate": "66AKRP",
                "type": "Other"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-026",
          "name": "Osmar Payan",
          "initials": "OP",
          "email": "osmarpayan@yahoo.com",
          "phone": "8632572491",
          "company": "FL Black Ram",
          "lotId": "lot-1",
          "spaceNumber": "31",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-027",
          "name": "Zach Peccarina",
          "initials": "ZP",
          "email": "zachpecarina@gmail.com",
          "phone": "",
          "company": "white Camper",
          "lotId": "lot-1",
          "spaceNumber": "32",
          "monthlyRate": 0,
          "startDate": "2026-04-01",
          "endDate": "2026-04-30",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Class A RV"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-028",
          "name": "Inocles T",
          "initials": "IT",
          "email": "",
          "phone": "",
          "company": "CHEVY 3500 HD TRUCK AND TRAILER  Trazil Family Transport LLC  Plate# REMR07",
          "lotId": "lot-1",
          "spaceNumber": "33",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "Chevrolet",
                "model": "",
                "year": null,
                "plate": "REMR07",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-029",
          "name": "Mary P",
          "initials": "MP",
          "email": "",
          "phone": "",
          "company": "trailer sold",
          "lotId": "lot-1",
          "spaceNumber": "34",
          "monthlyRate": 0,
          "startDate": "2026-03-01",
          "endDate": "2026-03-31",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": null,
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    },
    {
          "id": "t-030",
          "name": "Aylisa Davis",
          "initials": "AD",
          "email": "",
          "phone": "",
          "company": "LEGACY GROUP  white truck for sale",
          "lotId": "lot-1",
          "spaceNumber": "35",
          "monthlyRate": 0,
          "startDate": "2026-02-27",
          "endDate": "2026-03-27",
          "status": "active",
          "registrationStatus": "verified",
          "vehicle": {
                "make": "",
                "model": "",
                "year": null,
                "plate": "",
                "type": "Semi Truck"
          },
          "plateState": "FL",
          "truckNumber": "1520235",
          "trailerNumber": null,
          "insuranceDoc": null,
          "insurancePolicyNumber": null,
          "insuranceCompany": null,
          "insuranceExpDate": null,
          "autoRenew": false,
          "renewalPeriod": "monthly",
          "renewalRate": null,
          "paymentMethod": "manual",
          "autopayCard": null,
          "autopayNextDate": null,
          "payments": []
    }
    ],

  upcomingReservations: [
    { tenantId: 't-013', lotId: 'lot-1', space: 'T-67', startDate: '2025-01-15', endDate: '2026-01-14', amount: 295, status: 'pending'  },
    { tenantId: 't-014', lotId: 'lot-1', space: 'R-62', startDate: '2025-02-01', endDate: '2026-01-31', amount: 165, status: 'pending'  },
    { tenantId: 't-001', lotId: 'lot-1', space: 'T-08', startDate: '2025-01-10', endDate: '2026-01-09', amount: 295, status: 'renewal'  },
    { tenantId: 't-009', lotId: 'lot-1', space: 'T-52', startDate: '2025-01-01', endDate: '2025-12-31', amount: 295, status: 'renewal'  },
    { tenantId: 't-002', lotId: 'lot-1', space: 'R-14', startDate: '2025-03-01', endDate: '2026-02-28', amount: 220, status: 'confirmed' },
    { tenantId: 't-006', lotId: 'lot-1', space: 'R-22', startDate: '2025-05-01', endDate: '2026-04-30', amount: 190, status: 'confirmed' }
  ]
};

// ── Helpers ───────────────────────────────────────────────────────────────────
function getLot(id) { return APP_DATA.lots.find(function(l){ return l.id===id; }); }
function getLotName(id) { var l=getLot(id); return l?l.name:'—'; }
function getTenant(id) { return APP_DATA.tenants.find(function(t){ return t.id===id; }); }

function formatCurrency(n) {
  if (n==null||isNaN(n)) return '$0';
  return '$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0});
}
function formatDate(str) {
  if (!str) return '—';
  var d=new Date(str+'T00:00:00');
  if (isNaN(d)) return str;
  return d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
}
function timeAgo(iso) {
  if (!iso) return '—';
  var diff=Date.now()-new Date(iso).getTime(), mins=Math.floor(diff/60000);
  if (mins<1) return 'Just now';
  if (mins<60) return mins+'m ago';
  var hrs=Math.floor(mins/60);
  if (hrs<24) return hrs+'h ago';
  return Math.floor(hrs/24)+'d ago';
}

// ── Auto-Renewal Check ────────────────────────────────────────────────────────
// Returns tenants with autoRenew=true whose lease ends within 7 days (or already ended).
function checkAutoRenewals() {
  var today = new Date();
  today.setHours(0,0,0,0);
  var in7 = new Date(today.getTime() + 7*24*60*60*1000);
  return APP_DATA.tenants.filter(function(t) {
    if (!t.autoRenew || t.status === 'past' || t.status === 'cancelled') return false;
    if (!t.endDate) return false;
    var end = new Date(t.endDate+'T00:00:00');
    return end <= in7;
  });
}

// ── Renew Tenant Lease ────────────────────────────────────────────────────────
function renewTenantLease(tenantId) {
  var t = getTenant(tenantId);
  if (!t || !t.endDate) return null;
  var end = new Date(t.endDate+'T00:00:00');
  var newEnd = new Date(end);
  switch (t.renewalPeriod) {
    case 'weekly':    newEnd.setDate(end.getDate() + 7);     break;
    case 'quarterly': newEnd.setMonth(end.getMonth() + 3);   break;
    case 'annually':  newEnd.setFullYear(end.getFullYear()+1); break;
    default:          newEnd.setMonth(end.getMonth() + 1);   break; // monthly
  }
  t.endDate = newEnd.toISOString().split('T')[0];
  var rate = t.renewalRate || t.monthlyRate;
  var today = new Date().toISOString().split('T')[0];
  t.payments.unshift({ date: today, amount: rate, status: 'paid', method: t.paymentMethod === 'autopay' ? 'autopay' : 'manual' });
  return t;
}

// ── Toast ─────────────────────────────────────────────────────────────────────
function showToast(msg, type) {
  type = type||'success';
  var container = document.getElementById('toastContainer');
  if (!container) {
    container = document.createElement('div');
    container.id = 'toastContainer';
    container.style.cssText = 'position:fixed;bottom:24px;right:24px;z-index:9999;display:flex;flex-direction:column;gap:8px;pointer-events:none;';
    document.body.appendChild(container);
  }
  var colors={success:'#10b981',error:'#ef4444',warning:'#f59e0b',info:'#3b82f6'};
  var icons={success:'fa-check-circle',error:'fa-times-circle',warning:'fa-exclamation-triangle',info:'fa-info-circle'};
  var toast=document.createElement('div');
  toast.style.cssText='pointer-events:all;display:flex;align-items:center;gap:10px;background:white;border-left:4px solid '+(colors[type]||colors.success)+';border-radius:8px;padding:12px 18px;box-shadow:0 4px 20px rgba(0,0,0,0.15);font-size:0.875rem;font-family:Inter,sans-serif;color:#334155;min-width:260px;max-width:380px;transform:translateX(120%);transition:transform 0.3s ease;';
  toast.innerHTML='<i class="fas '+(icons[type]||icons.success)+'" style="color:'+(colors[type]||colors.success)+';flex-shrink:0;font-size:1rem;"></i><span>'+msg+'</span>';
  container.appendChild(toast);
  requestAnimationFrame(function(){ requestAnimationFrame(function(){ toast.style.transform='translateX(0)'; }); });
  setTimeout(function(){
    toast.style.transform='translateX(120%)';
    setTimeout(function(){ if(toast.parentNode) toast.parentNode.removeChild(toast); },300);
  },3500);
}

// ── CSV Export ────────────────────────────────────────────────────────────────
function exportToCSV(headers, rows, filename) {
  var esc=function(v){ var s=String(v==null?'':v); return (s.includes(',')||s.includes('"')||s.includes('\n'))?'"'+s.replace(/"/g,'""')+'"':s; };
  var csv=[headers.map(esc).join(',')].concat(rows.map(function(r){ return r.map(esc).join(','); })).join('\r\n');
  var blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});
  var url=URL.createObjectURL(blob);
  var a=document.createElement('a'); a.href=url; a.download=filename||'yardboss-export.csv';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
  showToast('Downloaded: '+(filename||'export.csv'),'success');
}

function generateId(prefix) {
  return (prefix||'id')+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
}
